blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import ArticleListView, ArticleDetailView, CategoryListView

app_name = 'blog'

urlpatterns = [
    path('', ArticleListView.as_view(), name='blog'),
    path('page/<int:page>/', ArticleListView.as_view(), name='blog'),
    path('<slug:slug>/', ArticleDetailView.as_view(), name='detail'),
    path('category/<slug:slug>/', CategoryListView.as_view(), name='category'),
    path('category/<slug:slug>/page/<int:page>/', CategoryListView.as_view(), name='category'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

can/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('', include('home.urls', 'home')),
    path('contact/', include('contact.urls', 'contact')),
    path('about/', include('about.urls', 'about')),
    path('services/', include('services.urls', 'services')),
    path('ckeditor/', include('django_ckeditor_5.urls')),
    path('account/', include('account.urls', 'account')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_jalali.db import models as jmodels
from account.models import User
from django_ckeditor_5.fields import CKEditor5Field

# my manager
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status="p")


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title
        
    def article_count(self):
        return self.articles.published().count()

    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published')
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ManyToManyField(Category, related_name="articles")
    description = CKEditor5Field('Text', config_name='extends')
    thumbnail = models.ImageField(upload_to="")
    publish = jmodels.jDateTimeField(default=timezone.now)
    created = jmodels.jDateTimeField(auto_now_add=True)
    update = jmodels.jDateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    reading_time_minutes = models.IntegerField()

    def __str__(self):
        return self.title

    



    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])

    objects = ArticleManager()

    class Meta:
        ordering = ["-publish"]

blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from django.http import Http404
from django.core.paginator import Paginator
from account.models import User


class ArticleListView(ListView):
    # model = Article
    template_name = 'article_list.html'
    # context_object_name = "articles"
    queryset = Article.objects.published()
    paginate_by = 2



class CategoryListView(ListView):
    paginate_by = 4
    template_name = 'category_list.html'
   
    def get_queryset(self):
        slug = self.kwargs.get('slug')
        self.category = get_object_or_404(Category.objects.active(), slug=slug)
        return self.category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context



class ArticleDetailView(DetailView):
    template_name = 'blog/article_detail.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.get_object()
        context['categories_article'] = article.category.active()
        context['categories'] = Category.objects.active()  
        return context

templates/blog/article_detail.html
{% extends "base.html" %}
{%block title%}{{articles.title}}{% endblock %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'django_ckeditor_5/dist/styles.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'django_ckeditor_5/dist/style-ck-2.css' %}" type="text/css">
<body>
     <!-- HEADER-SECTION -->
     <div class="home-header-section">
      
      <!-- BANNER-SECTION -->
      <div class="home-banner-section overflow-hidden">
          <div class="banner-container-box">
              <div class="container">
                  <div class="row">
                      <div class="col-lg-12 col-md-12 col-sm-12 mb-md-0 mb-4  text-center">
                          <div class="about-banner-text" data-aos="fade-up">
                              <h1 class="text-white about-h1" data-aos="zoom-out-left">Blog -{{ object.title }}</h1>
                              
                              
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- header and banner section -->
  <section class="blog-posts padding-top padding-bottom overflow single-post-blog overflow-hidden">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 col-lg-9">
          <div id="blog" class="single-post01 wow slideInLeft" data-aos="fade-up">
            <div class="post-item">
              <div class="post-item-wrap">
                <div class="post-image">
                  <a href="#">
                    <img alt="" src="{{object.thumbnail.url}}" style="width:100%; height: 300px;" />
                  </a>
                </div>
                <div class="post-item-description rastchin ">
                  <h2 class="mb-0">{{ object.title }}</h2>
                  <div class="post-meta">
                    <span class="post-meta-date color01"> {{object.publish|date:"Y-m-d H:i"}} </span>
                    
                    <span class="post-meta-date color01"> {{ object.reading_time_minutes }}دقیقه</span>
                    <span class="post-meta-comments color01">{{object.author.get_full_name}}</span>
                  </div>
                  <div class="ck-content ck-2">
                    {{object.description|safe}}
                  </div>
                </div>
                <div class="post-tags">
                  {% for cat in categories_article %}
                    <a href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                  {% endfor %}
                  <!--post-tags-->
                </div>
                <div class="comments" id="comments">
                  
                  
                  <!--comments-->
                </div>
                <!--post-item-wrap-->
              </div>
              <!--post-item-->
            </div>
            <!--single-post01-->
          </div>
          <!--col-->
        </div>
        <div class="sidebar sticky-sidebar col-lg-3 wow slideInRight">
          <div class="theiaStickySidebar">
            <div class="widget widget-newsletter">
              <form id="widget-search-form-sidebar" class="form-inline">
                <div class="input-group">
                  <input type="text" aria-required="true" name="q" class="form-control widget-search-form"
                    placeholder="Search for pages..." />
                  <div class="input-group-append">
                    <span class="input-group-btns">
                      <button type="submit" id="widget-widget-search-form-button" class="btn">
                        <span class="fa fa-search"></span>
                      </button>
                    </span>
                    <!--input-group-append-->
                  </div>
                  <!--input-group-->
                </div>
                <!--form-inline-->
              </form>
              <!--widget-->
            </div>
            <div class="widget">
              <div class="tabs">
                <ul class="nav nav-tabs" id="tabs-posts" role="tablist">
                  <li class="nav-item p-0">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#popular" role="tab"
                      aria-controls="popular" aria-selected="true">Popular</a>
                  </li>
                  <li class="nav-item p-0">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#featured" role="tab"
                      aria-controls="featured" aria-selected="false">Featured</a>
                  </li>
                  <li class="nav-item p-0">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#recent" role="tab"
                      aria-controls="recent" aria-selected="false">Recent</a>
                  </li>
                  <!--nav-tabs-->
                </ul>
                <div class="tab-content" id="tabs-posts-content">
                  <div class="tab-pane fade show active" id="popular" role="tabpanel">
                    <div class="post-thumbnail-list">
                      <div class="post-thumbnail-entry">
                        <a href="three-colum-sidbar.html"><img alt="" src="assets/images/side_post_img01.jpg"
                            class="img-fluid" /></a>
                        <div class="post-thumbnail-content">
                          <a href="three-colum-sidbar.html">A true story, that never been told!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 6m ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Technology</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <div class="post-thumbnail-entry">
                        <a href="three-colum-sidbar.html"><img alt="" src="assets/images/side_post_img02.jpg"
                            class="img-fluid" /></a>
                        <div class="post-thumbnail-content">
                          <a href="three-colum-sidbar.html">Beautiful nature, and rare feathers!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 24h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <div class="post-thumbnail-entry">
                        <a href="three-colum-sidbar.html"><img alt="" src="assets/images/side_post_img03.jpg"
                            class="img-fluid" /></a>
                        <div class="post-thumbnail-content">
                          <a href="three-colum-sidbar.html">The most happiest time of the day!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 11h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <!--post-thumbnail-list-->
                    </div>
                    <!--tab-pane-->
                  </div>
                  <div class="tab-pane fade" id="featured" role="tabpanel">
                    <div class="post-thumbnail-list">
                      <div class="post-thumbnail-entry">
                        <img data-aos="fade-up" alt="" src="assets/image/side_post_img03.jpg" />
                        <div class="post-thumbnail-content">
                          <a href="#">Beautiful nature, and rare feathers!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 24h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <div class="post-thumbnail-entry">
                        <img data-aos="fade-up" alt="" src="assets/image/side_post_img02.jpg" />
                        <div class="post-thumbnail-content">
                          <a href="#">The most happiest time of the day!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 11h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <div class="post-thumbnail-entry">
                        <img data-aos="fade-up" alt="" src="assets/image/side_post_img01.jpg" />
                        <div class="post-thumbnail-content">
                          <a href="#">New costs and rise of the economy!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 11h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <!--post-thumbnail-list-->
                    </div>
                    <!--tab-pane-->
                  </div>
                  <div class="tab-pane fade" id="recent" role="tabpanel">
                    <div class="post-thumbnail-list">
                      <div class="post-thumbnail-entry">
                        <img data-aos="fade-up" alt="" src="assets/image/side_post_img02.jpg" />
                        <div class="post-thumbnail-content">
                          <a href="#">The most happiest time of the day!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 11h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <div class="post-thumbnail-entry">
                        <img data-aos="fade-up" alt="" src="assets/image/side_post_img01.jpg" />
                        <div class="post-thumbnail-content">
                          <a href="#">New costs and rise of the economy!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 11h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <div class="post-thumbnail-entry">
                        <img data-aos="fade-up" alt="" src="assets/image/side_post_img03.jpg" />
                        <div class="post-thumbnail-content">
                          <a href="#">Beautiful nature, and rare feathers!</a>
                          <span class="post-date"><span class="far fa-clock"></span> 24h ago</span>
                          <span class="post-category"><span class="fa fa-tag"></span> Lifestyle</span>
                          <!--post-thumbnail-content-->
                        </div>
                        <!--post-thumbnail-entry-->
                      </div>
                      <!--post-thumbnail-list-->
                    </div>
                    <!--tab-pane-->
                  </div>
                  <!--tab-content-->
                </div>
                <!--tabs-->
              </div>
              <!--widget-->
            </div>
            <div class="widget widget-categories">
              <div class="widget-title font_weight_600">دسته بندی ها </div>
              <ul>
                {% for category in categories %}
                <li class="cat-item">
                  <a href="{% url 'blog:category' category.slug %}">{{ category.title }}</a>
                  <span class="cat-count-span">({{ category.article_count }})</span>
                </li>
                {% endfor %}
                
              </ul>
            </div>
            
            <div class="widget widget-tags">
              <h4 class="widget-title font_weight_600">تگ ها</h4>
              <div class="tags">
                {% for cat in categories_article %}
                  <a href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                {% endfor %}
                <!--tags-->
              </div>
              <!--widget-->
            </div>
            <!--theiaStickySidebar-->
          </div>
          <!--sidebar-->
        </div>
        <!--row-->
      </div>
    </div>
    <!--container-->
  </section>
  <!-- Footer-Section -->


   {% endblock content %}

templates/blog/article_list.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<body>
 <!-- HEADER-SECTION -->
 <div class="home-header-section">
  
  <!-- BANNER-SECTION -->
  <div class="home-banner-section overflow-hidden">
      <div class="banner-container-box">
          <div class="container">
              <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-12 mb-md-0 mb-4  text-center">
                      <div class="about-banner-text"  data-aos="fade-up">
                          <h1 class="text-white about-h1" data-aos="zoom-out-left">آخرین اخبار و رایتاپ ها</h1>
                          <p class="text-white banner-paragraph" data-aos="zoom-out-right">آخرین اخبار و به‌روزرسانی‌های و رایتاپ‌ها را از دست ندهید و همیشه به‌روز باشید</p>
                          
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
  <!-- header and banner section -->
  <section class="blog-posts overflow-hidden">
    <div class="container">
      <div class="row wow fadeInUp" style="visibility: visible; animation-name: fadeInUp">
        <div id="blog" class="col-xl-12" data-aos="fade-up">
          <div class="row">
            {% for article in object_list %}
            <div class="col-xl-6">
              <div class="float-left w-100 post-item border mb-4">
                <div class="post-item-wrap position-relative">
                  <div class="post-image">
                    <a href="#">
                      <img alt="" src="{{article.thumbnail.url}}"  style=" height: 300px;" />
                    </a>
                    {% if article.category.all %}
                      <span class="post-meta-category">
                          {% for cat in article.category.all %}
                            <a href="{% url 'blog:category' cat.slug %}">{{ cat.title }}</a>
                          {% endfor %}
                        </span>
                    {% endif %}
                    <!--post-image-->
                  </div>
                  <div class="post-item-description">
                    <span class="post-meta-date">{{article.publish|date:"Y-m-d"}} </span>
                    <span class="post-meta-date">{{article.reading_time_minutes}}دقیقه</span>
                    <span class="post-meta-comments">
                      <!-- <a href="#  # url 'author' blog.author "> {{ blog.author.get_short_name }} </a> -->
                      <a href="#"> {{ article.author.get_full_name }}</a>
                    </span>
                    <div class="rastchin">
                    <h2>
                      <a href="#">{{article.title}} </a>
                    </h2>
                    <p>
                      {{article.description|striptags|truncatewords:20}}
                    </p>
                    <a href="{% url 'blog:detail' article.slug %}" class="item-link text-decoration-none"><i class="fa fa-arrow-left"></i>  خواندن بیشتر   </a>
                    </div>
                    <!--post-item-description-->
                  </div>
                  <!--post-item-wrap-->
                </div>
                <!--post-item-->
              </div>
              <!--col-->
            </div>
            {% endfor %}
              <!--col-->
            </div>
          </div>
          <!--blog-->
        </div>

        <!--row-->
    {% if is_paginated %}  
      <div class="row">
          
        {% if page_obj.has_next %}
          <div class="col-xl-6">
            <div class="banner-btn discover-btn-banner float-left w-100 post-item  mb-4">
              <a href="{% url 'blog:blog' page_obj.next_page_number %}" class="item-link text-decoration-none "><i class="fa fa-arrow-left"></i>  پست های قدیمی  </a>
          </div></div>
        {% endif %}

        {% if page_obj.has_previous %}
          <div class="col-xl-6">
            <div class="banner-btn discover-btn-banner float-right w-110 post-item  mb-4">
              <a href="{% url 'blog:blog' page_obj.previous_page_number %}" class="item-link text-decoration-none  ">  پست های جدید  <i class="fa fa-arrow-right"></i></a>
          </div>
        {% endif %}
        </div>
      </div>
    {% endif %}
  </div>
      <!--container-->
    
    
   



  </section>
    <!-- Footer-Section -->
  {% endblock content %}