about/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from .views import about

app_name = 'about'

urlpatterns = [
    path('', about, name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

can/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('', include('home.urls', 'home')),
    path('contact/', include('contact.urls', 'contact')),
    path('about/', include('about.urls', 'about')),
    path('services/', include('services.urls', 'services')),
    path('ckeditor/', include('django_ckeditor_5.urls')),
    path('account/', include('account.urls', 'account')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import contact_view

app_name = 'contact'

urlpatterns = [
    path('', contact_view, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import services_view

app_name = 'services'

urlpatterns = [
    path('', services_view, name='services'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

about/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render


# Create your views here.

def about(request):
    return render(request, 'about.html')

contact/views.py
from django.shortcuts import render


# Create your views here.
def contact_view(request):
    return render(request, 'contact.html')

services/views.py
from django.shortcuts import render


# Create your views here.
def services_view(request):
    return render(request, 'services.html')

templates/about.html
<title>About us | SecHint</title>
{% extends "base.html" %}

{% block content %}

{% load static %}
    <!-- HEADER-SECTION -->
    <div class="home-header-section">

        <!-- BANNER-SECTION -->
        <div class="home-banner-section overflow-hidden">
            <div class="banner-container-box">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 mb-md-0 mb-4  text-center">
                            <div class="about-banner-text" data-aos="fade-up">
                                <h1 class="text-white about-h1">درباره ی ما</h1>
                                <p class="text-white banner-paragraph">مؤسسه‌ای پیشرو در ارائه‌ی دوره‌های آموزشی و خدمات
پیشرفته‌ی امنیت سایبری، همگام با دانش روز دنیا</p>
                                <div class="about-btn">
                                    <a href="{% url 'about:about' %}" class="text-decoration-none">Home <span class="about-text-color"> / About</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 mb-md-0 mb-4">
                            <div class="about-us-section-page" data-aos="fade-up">
                               <div class="row" >
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <h3  data-aos="zoom-out-left">24/7 Cyber Security Operation Center</h3>
                                    <br>
                                    <p></p>
                                     <ul class="list-unstyled about-us-list">
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Website Security Services</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">SIEM Threat Detection</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Content Delivery Network</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">24/7 Hours services</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Security Management</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Instant Malware Removal</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Website Hack Repair</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Instant Malware Removal</a></li>
                                     </ul>
                                     <div class="banner-btn-about discover-btn-banner about-order-services"><a href="{% url 'services:services' %}" class="text-decoration-none">سفارش سرویس</a>
                                         <a href="{% url 'contact:contact' %}" class="text-decoration-none play-button">راهنمایی رایگان</a></div></div>
                                 <div class="col-lg-5 col-md-5 col-sm-12">
                                     <div class="about-section-img">
                                         <figure class="mb-0"><img src="{% static 'assets/images/about-us-page-right-img.png' %}" alt="" class="">
                                         </figure>
                                     </div>
                                 </div>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ABOUT-US_SECTION -->
    <section class="about-us-section-start">
        <div class="about-right-icon position-relative" data-aos="fade-right"
        data-aos-offset="300"
        data-aos-easing="ease-in-sine">
            <figure class="whyus-icon"><img src="{% static 'assets/images/about-us-section-right-icon.png' %}" alt=""
                    class="img-fluid">
            </figure>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 class="text-center"  data-aos="fade-up"
                    data-aos-anchor-placement="top-bottom">چرا ما را انتخاب کنید</h3>
                        <p class="text-center">با پیشرفته‌ترین فناوری‌ها و راهکارهای اختصاصی، امنیت سایبری شما را به بالاترین سطح می‌رسانیم.
                        </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up"
                    data-aos-anchor-placement="bottom-bottom">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-round-icon1.png' %}" alt="">
                            </figure>
                        </div>
                        <h4>Security Services</h4>
                        <p class="security-services-p">Donec pede justo, fringilla vel, aliquet nec vulputate
                            eget, arcu. In enim justo, rhoncus ut imperdiet.</p>
                        <a href="about.html" class="text-decoration-none ">Learn More <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up"
                    data-aos-anchor-placement="bottom-bottom">
                        <div class="icons-rounded-box">
                            <figure class="mb-0 icon-color"><img src="{% static 'assets/images/about-round-icon2.png' %}" alt="">
                            </figure>
                        </div>
                        <h4>Data Privacy</h4>
                        <p class="security-services-p">Lorem ipsum dolor sit ametconsectetuer dipiscing
                            elitaenean commodo ligula eget dolor aenean massa.</p>
                        <a href="about.html" class="text-decoration-none ">Learn More <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up"
                    data-aos-anchor-placement="bottom-bottom">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-round-icon3.png' %}" alt="">
                            </figure>
                        </div>
                        <h4>Industry Certified</h4>
                        <p class="security-services-p">Integer tincidunt Cras dapibus bivamus ele mentum semper
                            nisienean vulputate eleife nd tellusenean leo ligula.</p>
                        <a href="about.html" class="text-decoration-none ">Learn More <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- CYBER-SECURITY-SECTION -->
    <section class="cyber-security-section overflow-hidden">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <div class="cyber-content-img" data-aos="fade-up-left">
                        <figure class="mb-0"><img src="{% static 'assets/images/cyber-security-left-img.png' %}" alt=""
                                class="cyber-security-provider-img">
                        </figure>
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1"></div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="cyber-content" data-aos="fade-up-right">
                        <h3 class="rastchin">ارائه دهنده <span class="cyber-text">امنیت سایبری</span> پیشرفته</h3>
                        <p class="security-services-p rastchin">امنیت شما در دنیای دیجیتال با راهکارهای پیشرفته ما تضمین شده است. با استفاده از تکنولوژی‌های روز و تیمی متخصص، ما تهدیدات سایبری را شناسایی و از شما در برابر آن‌ها محافظت می‌کنیم. هدف ما ایجاد یک محیط امن و مطمئن برای کسب‌وکارها و کاربران است تا بتوانند بدون نگرانی از امنیت، به رشد و توسعه خود ادامه دهند.

                        </p>
                        <p class="security-services-p cyber-p-margin-bottom rastchin">برای مشاوره رایگان با ما درارتباط باشید</p>
                        <div class="cyber-contact-btn">
                            <a href="contact.html" class="text-decoration-none">ارتباط با ما</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- boxes-section -->
    <div class="about-us-section-start cyber-boxes-section overflow-hidden">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/cyber-section-icon1.png' %}" alt="">
                            </figure>
                        </div>
                        <h3 class="counetr-heading"></h3>
                        <h5 class="cyber-boxes-text rastchin">پروژه های موفق</h5>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0 icon-color"><img src="{% static 'assets/images/cyber-section-icon2.png' %}" alt="">
                            </figure>
                        </div>
                        <h3 class="counetr-heading">
                        </h3>
                        <h5 class="cyber-boxes-text rastchin">حفاظت از مشتریان</h5>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="about-us-content"  data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/cyber-section-icon3.png' %}" alt="">
                            </figure>
                        </div>
                        <h3 class="counetr-heading"></h3>
                        <h5 class="cyber-boxes-text rastchin">ضمانت سرویس ها</h5>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="about-us-content"  data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/cyber-section-icon4.png' %}" alt="">
                            </figure>
                        </div>
                        <h3 class="counetr-heading"></h3>
                        <h5 class="cyber-boxes-text rastchin">تیم خبره</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Clients_section -->

    <!-- ABOUT-TEAM-SECTION -->
    
    <!-- Form-Section -->

{% endblock content %}

templates/services.html
<title>Services | SecHint</title>
{% extends "base.html" %}

{% block content %}

{% load static %}

    <!-- HEADER-SECTION -->
    <div class="home-header-section">

        <!-- BANNER-SECTION -->
        <div class="home-banner-section overflow-hidden">
            <div class="banner-container-box">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 mb-md-0 mb-4  text-center">
                            <div class="about-banner-text"  data-aos="fade-up">
                                <h1 class="text-white about-h1">سرویس ها</h1>
                                <p class="text-white banner-paragraph">
                                <br>
                                </p>
                                <div class="about-btn">
                                    <a href="{% url 'services:services' %}" class="text-decoration-none">Home <span class="about-text-color"> / Services</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ICONS_SECTION -->
    <section class="icons-section overflow-hidden">
        <div class="container">
        </div>
    </section>


    <!-- Services-About-us-Section -->
    <section class="about-us-section-start about-us-section-2 overflow-hidden">
        <div class="about-right-icon position-relative">
            <figure class="about2-left-img"><img src="{% static 'assets/images/about-section2-left-img.png' %}" alt=""
                    class="img-fluid">
            </figure>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 class="text-center offer-section-title"  data-aos="flip-up">آنچه ما ارائه می دهیم</h3>
                    <p class="text-center"  data-aos="fade-left">ما با ارائه راهکارهای امنیت سایبری پیشرفته و شخصی‌سازی شده، اطمینان می‌دهیم که هر جنبه از سیستم‌های شما به طور کامل محافظت شود

                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content about-margin-bottom " data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-section2-icon1.png' %}" alt="">
                            </figure>
                        </div>
                        <h4 class="rastchin">آموزش</h4>
                        <p class="security-services-p rastchin">اموزش های ما در برگیرنده تمام نیاز های شمااست تا به شما را اهدافتان برساند  </p>
                        <a href="about.html" class="text-decoration-none ">اطلاعات بیشتر <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content about-margin-bottom" data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0 icon-color"><img src="{% static 'assets/images/about-section2-icon2.png' %}" alt="">
                            </figure>
                        </div>
                        <h4 class="rastchin">تست نفوز</h4>
                        <p class="security-services-p rastchin">انجام آزمون نفوز سامانه وب، شبکه داخلی و نرم افزار های موبایل</p>
                        <a href="about.html" class="text-decoration-none ">اطلاعات بیشتر <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content about-margin-bottom" data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-section2-icon3.png' %}" alt="">
                            </figure>
                        </div>
                        <h4 class="rastchin">شکار تهدیدات سایبری</h4>
                        <p class="security-services-p rastchin">شکارتهدیدها بصورت فعال و بافرضیه پردازی تا  پیداکردن ردپاهای احتمالی مهاجمان در زیرساخت سازمان شما</p>
                        <a href="about.html" class="text-decoration-none ">اطلاعات بیشتر <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-section2-icon4.png' %}" alt="">
                            </figure>
                        </div>
                        <h4 class="rastchin">تیم قرمز</h4>
                        <p class="security-services-p rastchin">شبیه سازی یک حمله و تهیه گزارش کام و گام به گام</p>
                        <a href="about.html" class="text-decoration-none ">اطلاعات بیشتر <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up">
                        <div class="icons-rounded-box">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-round-icon1.png' %}" alt="">
                            </figure>
                        </div>
                        <h4 class="rastchin">مشاوره سازمانی</h4>
                        <p class="security-services-p rastchin">شمارا یاری میدهیم تا به نتایج و اهداف امنیتی سازمانتان برسید</p>
                        <a href="about.html" class="text-decoration-none ">اطلاعات بیشتر <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="about-us-content" data-aos="fade-up">
                        <div class="icons-rounded-box rastchin">
                            <figure class="mb-0"><img src="{% static 'assets/images/about-section2-icon6.png' %}" alt="">
                            </figure>
                        </div>
                        <h4 class="rastchin">اگاهی رسانی امنیت سایبری</h4>
                        <p class="security-services-p rastchin">مهم‌ترین نقطه‌ی ضعف امنیت سازمان شما عدم اگاهی کارکنانتان از تهدیدات سایبری کمین شده است</p>
                        <a href="about.html" class="text-decoration-none ">اطلاعات بیشتر <span class="forword-arrow"><i
                                    class="fa fa-angle-right"></i></span></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Services-Security-Option -->
    <section class="Services-Security-Option  Services-Security-Option-services-page overflow-hidden">
    <div class="about-right-icon position-relative">
        <figure class="whyus-icon"><img src="./assets/images/about-us-section-right-icon.png" alt="" class="img-fluid">
        </figure>
    </div>
      <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 mb-md-0 mb-4">
                <div class="about-us-section-page" data-aos="fade-up">
                   <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <h3  data-aos="zoom-out-left">24/7 Cyber Security Operation Center</h3>
                                    <br>
                                    <p></p>
                                     <ul class="list-unstyled about-us-list">
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Website Security Services</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">SIEM Threat Detection</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Content Delivery Network</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">24/7 Hours services</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Security Management</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Instant Malware Removal</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Website Hack Repair</a></li>
                                         <li><i class="fa-solid fa-shield-virus"></i><a href="#" class="text-decoration-none list-text">Instant Malware Removal</a></li>
                                     </ul>
                                     <div class="banner-btn-about discover-btn-banner about-order-services"><a href="{% url 'services:services' %}" class="text-decoration-none">سفارش سرویس</a>
                                         <a href="{% url 'contact:contact' %}" class="text-decoration-none play-button">راهنمایی رایگان</a></div></div>
                                 <div class="col-lg-5 col-md-5 col-sm-12">
                                     <div class="about-section-img">
                                         <figure class="mb-0"><img src="{% static 'assets/images/about-us-page-right-img.png' %}" alt="" class="">
                                         </figure>
                         </div>
                     </div>
                   </div>
                </div>
            </div>
        </div>
    
      </div>
  </section>


    <!-- Form-Section -->


{% endblock content %}